services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - app
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
  db:
    image: mysql:8.0
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rettiwt
    ports:
      - 3306:3306

